Repository UoaWDCC/volunteers, pull requests merged in 2024-05, with the labels that each got.

#77 Vol special/fix imports and btn
  web/package.json
  web/src/components/MainPageButtonHeadings.tsx
  web/src/components/Sponsors.tsx
  web/src/data/SponsorList.json
  web/src/pages/MainMenu.tsx
  web/yarn.lock
Labels: bug

#75 User Authentication with Google SignIn popup
  web/services/firebase.tsx
  web/src/components/Header.tsx
Labels: feature, Backend

#94 tailwindconfig
  web/package.json
  web/src/App.tsx
  web/src/components/MainGallery.tsx
  web/src/components/TestComponent.tsx
  web/src/main.tsx
  web/src/pages/MainMenu.tsx
  web/src/styles/componentStyles/Header.css
  web/src/styles/componentStyles/MainGallery.css
  web/src/styles/index.css
  web/tailwind.config.js
  web/yarn.lock
Labels: feature, tech debt
